# Generated by Django 4.1.5 on 2023-01-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherchart',
            name='AuburnID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
