# Generated by Django 4.1.5 on 2023-02-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_teacherchart_auburnid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='booktest/')),
            ],
        ),
    ]
